### ISSUE TITLE
Won't build

### ISSUE THREAD

**Issue by mchampine** [LauJensen/cloneit#1]
Hi Lau,

I've been struggling with making this work. Your article about this is now out of sync with this source, and the project doesn't work as-is.  (e.g. project.clj is out of date..).

I tried porting this to current versions of clojure and compojure, but it's turning out to be beyond my current compojure knowlege.  Any chance you might update it for clojure 1.2 and compojure 0.5.2 and write a new article that includes all the improvements?  This would make a great tutorial!

**Comment by LauJensen** [comment]
Hi,

Sorry about that :(

If I remember correctly, this fork is updated: https://github.com/pepijndevos/cloneit

I think I will actually do another tutorial with more updated tools: Enlive, Moustache and ClojureQL - Keep an eye on the blog :)

Lau

**Comment by mchampine** [comment]
Thanks, yes that worked great.  And yes, a tutorial like that would be very interesting. With a persistent store that would provide a quick start template for lots of interesting clojure web apps.
